name: Archive Release
on:
  workflow_run:
    workflows: ["zipping"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "modpack.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
