name: Archive Release
on:
  repository_dispatch:
    types: [trigger-release]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref_name}}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "modpack.zip"
          bodyfile: "modpack.zip"
         
