name: Create and release archive
on: 
  push:
    tags:
    - '*'    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Folder creation
      run: mkdir -p test

    - uses: actions/checkout@v3
    - name: Zip creation
      uses: thedoctor0/zip-release@0.7.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        type: 'zip'
        filename: 'test/modpack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.jar* test'
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cancel if build did not work
      if: ${{ needs.build.result == 'failure' }}
      run : exit 1
    - run: echo "Job failed and cancelled."
  release:
    needs: check
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref_name}}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'test/*'
         
