on: 
  push:
    tags:
    - '*'    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Archive Creation
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'modpack.zip'
        directory: "./"
        exclusions: '*.git* /*node_modules/* .editorconfig *.jar*'
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cancel if build did not work
      if: ${{ needs.build.result == 'failure' }}
      run : exit 1
    - run: echo "Job failed and cancelled."
  release:
    needs: check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref_name}}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./modpack.zip"
          bodyfile: "./modpack.zip"
         
