name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
    - uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'modpack.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        path: '/epic-modpack/'
  notify:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifact: "modpack.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
